baseurl:

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default

collections:
  wat-hoe:
    output: true
  nieuws:
    output: false
  tools:
    output: true
